### ISSUE TITLE
German "Umlaute" not working

### ISSUE THREAD

**Issue by Carunga** [sytone/obsidian-remote#11]
Hello,
nice work, for me this is really usefull stuff. And it works great. Thanks a lot and keep up the great work. I do have one problem though:

**Describe the bug**
not all charackters on a German keyboard work as expexted. üäö do not function at all (when pressed no letter apperas on the creen)

**To Reproduce**
install docker image
set - GUAC_KEYBOARD_LAYOUT=de-de-qwertz in docker-compse
open webgui of obsidian remote
press ä ü or ö

I could not find anything in the logs.

Any ideas how to fix this?

**Comment by sytone** [comment]
Not sure on this one. I would have to look at the base containers to see how to override the keyboard.

**Comment by Carunga** [comment]
Thanks for the answer. The solution is quite simple, but not easy to find:

in the docker-compose file set 
    environment:
       - KEYBOARD=en-us-qwerty  
for German it is de-de-qwertz - a list of other possible values (not tested) can be found at https://hub.docker.com/r/linuxserver/digikam

I think this should work for all images based on https://github.com/linuxserver/docker-baseimage-rdesktop-web

Looks like I will be using your image on a daily basis now!

**Comment by sytone** [comment]
Great to hear it is working for you and it can help you out! Ill update the readme.
