### ISSUE TITLE
How to add language(e.g. Chinese) support

### ISSUE THREAD

**Issue by lmingzhi** [sytone/obsidian-remote#12]
**Describe the bug**

The characters of non-English look likes square. 

**To Reproduce**
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/25837153/170165604-3cbce615-6b57-4efd-9283-871da86f4e1c.png">

**Comment by aaron-jang** [comment]
Same happens to me.

**Comment by sytone** [comment]
Thanks for this, updated the documentation with this information.
