### ISSUE TITLE
Add Copy + Paste Functionality

### ISSUE THREAD

**Issue by GrunclePug** [sytone/obsidian-remote#13]
**Is your feature request related to a problem? Please describe.**
Copy and paste do not work, ie i cannot copy text from a blog and paste it into obsidian, this makes adding in depth concepts quite frustrating, either having to type it all out by hand, or build the md files on my laptop and sftp them onto my server

Additionally, the same issue with images, it would be nice to drag and drop an image into your vault without opening the file system button

**Describe the solution you'd like**
Please add support for copy and paste from client to web gui

**Describe alternatives you've considered**
If drop in copy and paste isnt possible, is it possible to have a copy / paste box? like how you can go to upload and upload a file, if you can go to a note, open the paste box, paste your text, hit done and it would insert it into your note at your current context

**Comment by sytone** [comment]
Use the x to copy and paste. When you click on it you can paste the text into the box. Then in the app you can paste. There is no way to paste from the client to the remote session directly.

**Comment by GrunclePug** [comment]
> Use the x to copy and paste. When you click on it you can paste the text into the box. Then in the app you can paste. There is no way to paste from the client to the remote session directly.

Ahhh okay thanks! didn't realise that was a text box, thought it was just a work in progress render or something. might be a good idea to add a placeholder for it along the lines of "Paste text" or something idk.
Thanks for the reply!
