### ISSUE TITLE
Dealing with Obsidian update notifications

### ISSUE THREAD

**Issue by brinycoolie** [sytone/obsidian-remote#16]
**Describe the bug**
I just installed Obsidian Remote via docker-compose and as soon as I made my first note a green notification appeared to inform me that a new major version of Obsidian was available. My question is will this be taken care of by routine updates of the docker image or is there a process for the user to perform this update?

**To Reproduce**
install from ghcr.io/sytone/obsidian-remote:latest

**Expected behavior**
just need to know if the maintainer 'sytone' will take care of the update and how frequently.... and perhaps add a paragraph in the docs to let user know what to do .

**Screenshots**

**Desktop (please complete the following information):**

-     Ubuntu server 20.04
-     Chrome

**Smartphone (please complete the following information):**

**Additional context**
MOre of a request for documentation than a bug request. Great to see this in docker

**Comment by brinycoolie** [comment]
0.15.9 is the installed version I think. Only a vice with Obsidian so forgive my unfamiliarity.

**Comment by punchy98** [comment]
The current version used by the dockerfile is 0.13.31. I opened a PR for moving up to 0.15.9, currently waiting on the repo maintainer to review

**Comment by sytone** [comment]
Updated to 0.15.9, not sure what happened with the PR. Was showing empty. Also added comments on the container auto updating.
