### ISSUE TITLE
could add a  passwd for login

### ISSUE THREAD

**Issue by zhijie-zhang** [sytone/obsidian-remote#17]
If we are on the public network, the ip:port will be exposed, and the data will be tampered with by others, so it will be better to add login authentication

**Comment by fahrenhe1t** [comment]
If you install obsidian-remote in Docker, you could proxy it through Nginx Proxy Manager, and use an access list to provide user authentication.  The obsidian-remote container would have to be on the same network as Nginx Proxy Manager.  This video talks about it: https://www.youtube.com/watch?v=G9voYZejH48

**Comment by sytone** [comment]
In the readme https://github.com/sytone/obsidian-remote#hosting-behind-a-reverse-proxy has an example setup in nginx to proxy to the container.

**Comment by sytone** [comment]
Added notes from this thread to docs. Thanks @fahrenhe1t
