### ISSUE TITLE
Copy/Paste From External Source No Worky

### ISSUE THREAD

**Issue by Vertex21** [sytone/obsidian-remote#19]
**Describe the bug**
Inability to paste copied content from outside of the obsidian-remote browser tab into an obsidian document. And vice versa, can't copy content from an obsidian-remote document to any other program, like notepad for instance.

**To Reproduce**

1. Open or create any document in obsidian-remote
2. Create some text if no text exists
3. Select text and Ctrl+V or right click and "copy"
4. Go to another program like Notepad or another browser tab and try to paste.
5. Nothing gets pasted.

**Expected behavior**
I expected the data to be copied to PC's clipboard for use anywhere I wanted to paste it. And on the other side, I expected data from PC's clipboard to be pasted into obsidian-remote.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 x64 PC accessing obsidian-remote through docker container on Contabo Ubuntu VPS
Browser is Chrome
Version 106.0.5249.103 (Official Build) (64-bit)

**Comment by sytone** [comment]
Thanks @Hoempi added guidance to readme and closing up the issue.
