### ISSUE TITLE
Chinese display garbled characters

### ISSUE THREAD

**Issue by zhijie-zhang** [sytone/obsidian-remote#22]
Chinese display garbled characters.

how to fix that

**Comment by sytone** [comment]
I am not sure what you mean. Did you install the font using the guidance in the readme?

**Comment by sytone** [comment]
Following up. Did you follow the instructions on the read me to install the correct font?

**Comment by zhijie-zhang** [comment]
Fixed , Follow readme
thanks


在 2022/11/28 2:03, Sytone 写道:

**Comment by sytone** [comment]
Closing up issue as resolved.
