### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by layanto** [sytone/obsidian-remote#24]
**Describe the bug**
Image is not loading, whether embedded or directly opening an image file in vault. Embedded PDF also not showing. Note that the same vault works with obsidian running on the host machine (Windows 10).

**To Reproduce**

1. Open an image file in vault or open md with embedded image or pdf file
2. No image or pdf displayed. Electron developer tool says error finding the file.

**Expected behavior**
Image shown in obsidian.

**Screenshots**
![image](https://user-images.githubusercontent.com/245078/201500661-9ff8c11c-53cc-46b6-aa6c-144c0b934f73.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 1.0.3

**Additional context**
From Electron developer tool, the img src of the image is in the form of app://local/vaults/vault_name/attachments/file.jpeg. This is similar path to what I see on Windows obsidian opening the same vault - app://local/C:/Data/Obsidian/vault_name/attachments/file.jpeg

**Comment by sytone** [comment]
Do you have an example vault I could use to reproduce?

**Comment by layanto** [comment]
[test.zip](https://github.com/sytone/obsidian-remote/files/10145657/test.zip)

Above Obsidian test vault I created by deleting most of the content from my vault.

1. Note that embedded image in a md file is not loaded for: resources\books\M\Make It Stick
2. Note that image file also not loaded when viewed direction: areas\inbox\Graph Database Problem.jpg or resources\files\2021\06\Book - Make It Stick.png

**Comment by layanto** [comment]
Turns out issue is because I have icon as part of directory name. No issue with this on Windows though.
![image](https://user-images.githubusercontent.com/245078/212439752-958f6090-b121-484b-a699-ae9e972b08be.png)
![image](https://user-images.githubusercontent.com/245078/212439764-9780bb33-ef4c-45e3-bd32-53adc5514d07.png)
Removing all icons from directory name, image now loading correctly.

**Comment by layanto** [comment]
And the other issue was I was pointing docker volume to bind to Windows directory.  Now I am using Obsidian Remote with vault stored in wsl2.
