### ISSUE TITLE
x86_64 image possible?

### ISSUE THREAD

**Issue by Phileep** [sytone/obsidian-remote#34]
I am unable to install as I have a x86_64 system (synology NAS) - would a build be possible for this type of server?

**Comment by drewbitt** [comment]
ghcr.io/sytone/obsidian-remote:latest works perfectly for me on a x86_64 unraid NAS. The base dockerfile.

**Comment by sytone** [comment]
Was this resolved?

**Comment by Phileep** [comment]
I have not re-tried as yet, but I accept I may have mis-diagnosed the issue

Closing until I have a better description of issue (if any)
