### ISSUE TITLE
Screen goes to black while loading community themes screen

### ISSUE THREAD

**Issue by basicallybene** [sytone/obsidian-remote#4]
1. Go to settings
2. Click on appearance tab
3. Click on manage (themes)
4. Scroll down a bit
5. Screen goes black

**Screenshots**
![image](https://user-images.githubusercontent.com/65005364/158436060-377a0839-cb54-41e2-8efa-5eec8f181de3.png)

**Desktop **
 - Windows 10 20H2
 - Browser: Edge
 - Docker Desktop 4.5.1 (74721)

**Comment by sytone** [comment]
I have had a chance to lok and I can re-produce. Looking at the session logs when you hit the apperence UI it is spammed with 

`[598:0319/035122.401055:ERROR:broker_posix.cc(46)] Received unexpected number of handles`

**Comment by sytone** [comment]
@basicallybene  Ok, resolved the issue and tested locally and it no longer happens. Pull the v0.0.2/latest image and let me know if it is resolved.

**Comment by sytone** [comment]
Closing this up as I can no longer re-produce.
