### ISSUE TITLE
Paste into Obsidian-remote?

### ISSUE THREAD

**Issue by pr0fsmith** [sytone/obsidian-remote#45]
**Describe the bug**
Cannot paste into my notebook from my desktop.

**To Reproduce**

1. Copy something from your desktop
2. Attempt to paste it into Obsidian notebook
3. It will not paste

**Expected behavior**
Data will paste into notebook

**Desktop (please complete the following information):**

- OS: Linux Mint
- Browser Firefox

**Comment by rekab72** [comment]
@pr0fsmith From the last section of the README [https://github.com/sytone/obsidian-remote#copypaste-from-external-source](url)

**Copy/Paste From External Source**
Click on the circle to the left side of your browser window. In there you will find a textbox for updating the remote clipboard or copying from it.

![2023-02-04-115057_1920x1080_scrot](https://user-images.githubusercontent.com/74030695/216779684-b4967568-1367-4221-9fe4-07631ff7a0c4.png)
![2023-02-04-115042_1920x1080_scrot](https://user-images.githubusercontent.com/74030695/216779690-3dc05594-a1ba-4e15-be25-c350a323988e.png)

**Comment by pr0fsmith** [comment]
I see.  My problem was I was trying to use ctrl+c and ctrl+v to paste into Obsidian.  I was able to paste into it by right clicking and selecting paste.  Thanks.
