### ISSUE TITLE
Please add git to the container

### ISSUE THREAD

**Issue by guitaristtom** [sytone/obsidian-remote#5]
**Is your feature request related to a problem? Please describe.**
Yes.

I use obsidian-git to sync my two vaults between my GitLab instance and the various computers and devices I use on a daily basis.

**Describe the solution you'd like**
If git is added to the container, then for anyone who is using git to sync their vault between computers, like myself, then it can be set up and working without needing to fork the container and install it.

**Comment by guitaristtom** [comment]
Nevermind, figured out that the linuxserver.io container mods work with their base image.

https://github.com/linuxserver/docker-mods/tree/universal-git

**Comment by guitaristtom** [comment]
Although, I did have to change the `config` path from `/config/.config/obsidian` to just `/config`, since the SSH keys were _by default_ being stored in `/config`.

Might be a good thing to change the defaults for?

**Comment by guitaristtom** [comment]
![image](https://user-images.githubusercontent.com/6890628/158734964-15426287-88b7-49d8-a986-df1a1bb2ad03.png)

**Comment by sytone** [comment]
Thanks for this, I have updated the readme to cover this information and updated the path of the directory to just be `/config`
