### ISSUE TITLE
How does Obsidian Remote work? Would it be possible to have an Obsidian server on my Mac without Docker? 

### ISSUE THREAD

**Issue by YousufSSyed** [sytone/obsidian-remote#50]
Isn't Obsidian a closed source app? How are you able to take an Electron app, put it into a Docker container and turn it into a localhost server? Is there anything I could Google to learn more about the way it works, or anything to read about it? I did some googling on turning Electron apps into servers but didn't find good results.

Also, I've been trying to find a way to somehow run multiple instances of Obsidian on my Mac. What I'm going for is to have multiple vaults open simultaneously and I'd be able to access them in different app icons on my dock. If I opened two vaults in my one Obsidian app, it would show as 2 different windows which I don't want. Creating a 2nd copy of the app doesn't solve it either, it will just open in the same windows for some reason.

The thing about running it in a Docker container is that it would require running a Linux VM underneath and that would take up lots of resources.

**Comment by sytone** [comment]
The container just uses a linux image to load the obsidian app and then show it via a browser as a remote desktop app. Look though the docker file as it uses the linux server images as a base.

**Comment by YousufSSyed** [comment]
I'm not very familiar with Docker and haven't really used containers before. I looked through the repo and it looks like it installed some apt packages, and I found the `autostart` file that contains this:

```
/squashfs-root/obsidian --no-sandbox --disable-dev-shm-usage --disable-gpu --disable-software-rasterizer
```

Is this what launches Obsidian as a remote desktop app? I don't understand how that's possible. I'd still like to know where I could read about this or terms to look up. Would this be possible on a Mac, ideally without a Linux VM?

If it is like accessing an app from a remote desktop, how's the resolution and performance? Is it lower like comparing a RDP session to using the device in-person, if that makes sense?

**Comment by sytone** [comment]
These packages and scripts are run in a container, it is like a virtual machine. To run this you need to have an environment running docker. When the container starts it enables a website that if you connect to will show Obsidian in your browser. This is just a web version of RDP.

**Comment by YousufSSyed** [comment]
Oh I figured that out a while while waiting for a response, thanks anyway. Its simply an RDP session that shows in the browser. I thought this app was doing something special with Obsidian or something with Electron, something that it normally wouldn't do, to make it show up on as a website accessible in your browser.
