### ISSUE TITLE
Change base image to kasmvnc

### ISSUE THREAD

**Issue by ilkersigirci** [sytone/obsidian-remote#51]
Recently, linuxserver webtop move to [kasm base image](https://github.com/linuxserver/docker-baseimage-kasmvnc) for better performance. Related blog post is [here](https://www.linuxserver.io/blog/webtop-2-0-the-year-of-the-linux-desktop). 

I think we can also profit from performance improvements if the base image will be changed.

**Comment by ilkersigirci** [comment]
I have tried to implement it myself in the following dockerfile and it is working perfectly. Seamless clipboard  and scrolling thanks to kasmvnc

```dockerfile
FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye
RUN \
    echo "**** install packages ****" && \
        # Update and install extra packages.
        apt-get update && \
        apt-get install -y --no-install-recommends \
            # Packages needed to download and extract obsidian.
            curl \
            libgtk-3-0 \
            libnotify4 \
            libatspi2.0-0 \
            libsecret-1-0 \
            libnss3 && \
    echo "**** cleanup ****" && \
        apt-get autoclean && \
        rm -rf \
        /var/lib/apt/lists/* \
        /var/tmp/* \
        /tmp/*

ARG OBSIDIAN_VERSION=1.1.16

RUN dl_url="https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/obsidian_${OBSIDIAN_VERSION}_amd64.deb" && \
    curl --location --output obsidian.deb "$dl_url" && \
    dpkg -i obsidian.deb

ENV \
    CUSTOM_PORT="3000" \
    TITLE="Obsidian v$OBSIDIAN_VERSION" \
    # FM_HOME="/vaults"
    FM_HOME="/config"

# add local files
COPY /root /

EXPOSE 3000
VOLUME ["/config","/vaults"]

```

NOTE: `/squashfs-root/obsidian --no-sandbox --disable-dev-shm-usage --disable-gpu --disable-software-rasterizer` should be changed with `/usr/bin/obsidian`

**Comment by crosbyh** [comment]
I agree this would be an incredible change to see merged in. The kasm base image is so much faster!

**Comment by sytone** [comment]
Done, thanks for the contrib!
