### ISSUE TITLE
Obsidian v1.3+ may need the installer to be updated

### ISSUE THREAD

**Issue by layanto** [sytone/obsidian-remote#57]
Noticed this pop up advising of major installer update requiring re-installing of Obsidian (not just update). See below. Does this require a new release of Obsidian-Remote docker image?

![image](https://github.com/sytone/obsidian-remote/assets/245078/4809335c-f8e5-4732-9c14-4a7c24af465a)

**Comment by sytone** [comment]
PR #58 updated the version so will have the latest version in it if you update the container.

**Comment by sytone** [comment]
PR #58 updated the version so will have the latest version in it if you update the container.

**Comment by layanto** [comment]
Has the image ghcr.io/sytone/obsidian-remote:latest been  updated to include PR #58? I tried re-creating my container and pulling latest image but the installer version is still v0.15.9.
