### ISSUE TITLE
Credit Upstream maybe?

### ISSUE THREAD

**Issue by codefaux** [sytone/obsidian-remote#65]
So I found this via Unraid Community Apps -- I don't know what Obsidian is. Whatever your project is, you didn't build Obisidan. You didn't link to it. You just include it. In your initial project description, you need to make the word Obsidian a link to the Obsidian project. It feels obvious, but it isn't.

https://obsidian.md/

**Comment by sytone** [comment]
I'll add an update in the readme. This came from an ask on the obsidian site so it was obvious at the time.
