### ISSUE TITLE
URL link does not work

### ISSUE THREAD

**Issue by smbricchi** [sytone/obsidian-remote#69]
Using obsidian-remote i can click on an URL link but nothing happen.
Is this a normal behavior for obsidian remote or doe I have to do something to activate this behavior.
I am quite new with obsidian and need some help.

I created a note in obsidian and entered the following URL:

[Obsidian Help]('http://help.osidian.md')

When i click on the link nothing happen.

The error i see in debug mode is the following:

app.js:1 TypeError: Failed to construct 'URL': Invalid URL
    at lk (app.js:1:906629)
    at t.getClickableTokenAt (app.js:1:1259883)
    at t.onEditorLinkMouseover (app.js:1:1275223)
    at HTMLDivElement.s (enhance.js:1:10423)

An URL link on an obsidian installed local does work.

**Comment by smbricchi** [comment]
Problem solved.

**Comment by smbricchi** [comment]
Problem was not a issue was an misunderstanding of the setup.

**Comment by JS1Dev** [comment]
@smbricchi, what was it that you did so that clicking on a link works?  When I click on the link in read or write mode, nothing happens for me.  I must be misunderstandings something as well...
![image](https://github.com/sytone/obsidian-remote/assets/148407073/498ac84d-acd6-4829-9cd9-3b898626551e)
