### ISSUE TITLE
Missing TZ variable

### ISSUE THREAD

**Issue by Fonsos** [sytone/obsidian-remote#7]
**Is your feature request related to a problem? Please describe.**
There are plugins that use the current time of the system to work. Right now it shows an hour less than my Timezone.

**Describe the solution you'd like**
 It would be awesome to set it as a TZ variable in the docker container.

**Comment by sytone** [comment]
You can, this is based off the linuxserver images. TZ is an environment variable you can set. Did you try this via the CLI or compose and were there issues?

**Comment by sytone** [comment]
Just rant the docker command with TZ=Asia/Calcutta and checked the running container and saw it was in IST.

`docker run --rm -it -e TZ=Asia/Calcutta -e PUID=1000 -e PGID=1000 -v D:/ob/vaults:/vaults -v D:/ob/config:/config/.config/obsidian -p 8080:8080 --name obsidian-remote obsidian-remote:latest ` 

![image](https://user-images.githubusercontent.com/1399443/159771832-f3edeaf2-3778-42de-9b6a-94c98bb3cea1.png)

**Comment by Fonsos** [comment]
I did it on Unraid, I added a variable TZ with the value Europe/Madrid:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/9643213/159779770-f3dd8efa-0354-4406-bfd5-ab2211838b70.png">

But I got 1 hour less: 
<img width="113" alt="image" src="https://user-images.githubusercontent.com/9643213/159779816-c61aefa7-7b97-434d-8eac-1fdf6031e89c.png">

**Comment by sytone** [comment]
Just made a new build, v0.0.4 which will push date information to the log when the container starts. I am guessing it is a Time Zone issues with daylight savings.

**Comment by Fonsos** [comment]
That can be the cause of the 1 hour gap.

Here is the log info:
![image](https://user-images.githubusercontent.com/9643213/159863127-30a80b39-5e4b-4fab-9201-c8747c1f8dc9.png)

I think that's the problem.

**Comment by sytone** [comment]
ok, I am not sure why the image is not switching time zones to DST for your area. Did Madrid make any changes to the dates that DST start and stop recently? Ill have to look at the base image to see if there is any issues with the base TZ stuff. Will probably not get time until the weekend.

**Comment by Fonsos** [comment]
Sorry for the late reply.

I have looked when is the day when the time is changing and it's tomorrow (I didn't know when it was changing this year, sorry 😅, I hope this nonsense finish soon), so that you comment might be the problem.

If you want, we can wait for the Sunday morning and I'll comment if the time is the same in both, time zone and current time and there's no error. And then you can close this issue, and if this occurs next time when the hour change is coming, I'll wait for the hour change.

**Comment by sytone** [comment]
Happy to wait. Let me know if the time is correct when it switches over.

**Comment by Fonsos** [comment]
The hour has changed:
![Screenshot_20220327-194526__01](https://user-images.githubusercontent.com/9643213/160293832-33ab0089-9e6b-42a3-847b-d50bf98d2795.jpg)
Now we are at UTC + 2 so it should be right, but internally it displays UTC hour, without those 2 hours.

**Comment by benglim** [comment]
I had the same problem. Had to configure manually "dpkg-reconfigure tzdata"

**Comment by masterwishx** [comment]
I have right TZ in console (Israel Date Time ) 
but when use @time from plugin it use UTC (-3 hours)

**Comment by sytone** [comment]
Adding reconfigure to the initial config script to force it as per comment by @benglim.

```
echo "Running dpkg-reconfigure -f noninteractive tzdata"
echo "${TZ}" >/etc/timezone
dpkg-reconfigure -f noninteractive tzdata
```
