### ISSUE TITLE
fails to run on podman arm64

### ISSUE THREAD

**Issue by mosajjal** [sytone/obsidian-remote#89]
Hi, 

the following fails with an x11 error 

```
podman run --rm -it \
   -v /obsidian/vaults:/vaults \
   -v /obsidian/config:/config \
   -p 10007:8080 \
   docker.io/sytone/obsidian-remote:arm64
```

```
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/xrdp-sesman/: No such file or directory
```

assuming `docker` will also fail. is there any reason why the dockerfile for arm needs x11 to be installed in the first place?

**Comment by chmac** [comment]
I'm just guessing from having read a few other tickets, I think that this container runs X inside docker, and then runs VNC in the browser. I believe that's the basic architecture to run a desktop app in a browser, and so I guess that X is a requirement for that reason. But sadly I can't help you with the error.

**Comment by mosajjal** [comment]
thanks for this. I ended up using `lscr.io/linuxserver/obsidian:latest` from [this repo](https://github.com/linuxserver/docker-obsidian) and it works great! will close this one.
