### ISSUE TITLE
Where to edit port configuration?

### ISSUE THREAD

**Issue by h3rb1n4t0r** [sytone/obsidian-remote#9]
I am trying to deploy an obsidian-remote container via docker compose using the portainer stack function with the suggested docker compose. Since 8080 is already occupied by another container, i tried to use 6060:6060 which however results in an error when accessing the URL. I suppose, that the basic configuration uses 8080:8080. What file(s) do i have to edit to fire it up on 6060:6060?

**Comment by sytone** [comment]
Use **6060:8080** this maps port 6060 on your host to port 8080 in the container.

**Comment by h3rb1n4t0r** [comment]
Thank you sir and have a happy easter!
