### ISSUE TITLE
Can't copy or paste attachments from desktop, and copying and pasting text is terrible

### ISSUE THREAD

**Issue by mathisgauthey** [sytone/obsidian-remote#94]
**Describe the bug**
Can't copy and paste attachments at all, even using the import file provided in the UI,
Copy and pasting text is painful as well.

**To Reproduce**
Build an image using : 

```
FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye

LABEL maintainer="github@sytone.com" \
      org.opencontainers.image.authors="github@sytone.com" \
      org.opencontainers.image.source="https://github.com/sytone/obsidian-remote" \
      org.opencontainers.image.title="Container hosted Obsidian MD" \
      org.opencontainers.image.description="Hosted Obsidian instance allowing access via web browser"

# Update and install extra packages.
RUN echo "**** install packages ****" && \
    apt-get update && \
    apt-get install -y --no-install-recommends curl libgtk-3-0 libnotify4 libatspi2.0-0 libsecret-1-0 libnss3 desktop-file-utils fonts-noto-color-emoji git ssh-askpass && \
    apt-get autoclean && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# Set version label
ARG OBSIDIAN_VERSION=1.5.8

# Download and install Obsidian
RUN echo "**** download obsidian ****" && \
    curl --location --output obsidian.deb "https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/obsidian_${OBSIDIAN_VERSION}_amd64.deb" && \
    dpkg -i obsidian.deb

# Environment variables
ENV CUSTOM_PORT="8080" \
    CUSTOM_HTTPS_PORT="8443" \
    CUSTOM_USER="" \
    PASSWORD="" \
    SUBFOLDER="" \
    TITLE="Obsidian v${OBSIDIAN_VERSION}" \
    FM_HOME="/vaults"

# Add local files
COPY root/ /
EXPOSE 8080 8443
VOLUME ["/config","/vaults"]

# Define a healthcheck
HEALTHCHECK CMD curl --fail http://localhost:8080/ || exit 1
```

Built it locally : 

```
docker build --pull --rm `
  -f "Dockerfile" `
  -t obsidian-remote:latest `
  "."
```

Run it : 

```
docker run --rm -it `
  -v D:/ob/vaults:/vaults `
  -v D:/ob/config:/config `
  -p 8080:8080 `
  obsidian-remote:latest bash
```

Run it, and try copy pasting text or images.

We can only copy images, use your mouse to open the clipboard and paste text using it,

Import from the top menu doesn't work at all for images.

![image](https://github.com/sytone/obsidian-remote/assets/46576952/151922cd-4655-46c6-b85a-d678e7d4deb6)

**Expected behavior**
I should be able to copy and paste.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox LTS

Thanks for your work, but in the present case I can't use it at all as I need copy pasting. Hoping we can find a way to upgrade this behavior !

**Comment by adamzachyang** [comment]
It seems that it's not recommended to use Firefox with KasmVNC as there are known issues with it although they aren't explicitly mentioned. Source: https://kasmweb.com/kasmvnc/docs/master/clientside.html

**Comment by mathisgauthey** [comment]
> It seems that it's not recommended to use Firefox with KasmVNC as there are known issues with it although they aren't explicitly mentioned. Source: https://kasmweb.com/kasmvnc/docs/master/clientside.html

Wow thanks for pointing this out, I did not consider it at all.

The setup looks really promising on a Chrome instance and would definitely fix an issue I had while using it at work. Thanks for taking the time, I'm buying a Rasb Pi right away to play around with it !

**Comment by adamzachyang** [comment]
@mathisgauthey No worries! I still find sometimes I can't scroll anymore in documents but just refreshing the page seems to help that. I've made a fork of this repo for a setup that works on the Raspberry Pi 4 if it helps https://github.com/adamzachyang/obsidian-remote-rpi, you just need to build the image locally on the Raspberry Pi
